version: '3.3'
services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb-api-tarefas
    environment:
    - MONGO_DATA_DIR=./data/db
    - MONGO_LOG_DIR=./log
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
      - ./log:/log